FROM python:3.14.0a4-alpine3.21

WORKDIR /home/python

RUN python -m venv . && source bin/activate

RUN pip install . https://github.com/croedel/MTECmqtt/archive/refs/heads/main.zip

COPY ./config.yaml ./mtecmqtt/config.yaml

ENV XDG_CONFIG_HOME /home/python

CMD [ "mtec_mqtt" ]